parameters:
#    categorias.example.class: Plateria\CategoriasBundle\Example

services:
#    categorias.example:
#        class: %categorias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
